"""initial

Revision ID: db1de479b63e
Revises: 
Create Date: 2026-06-18 11:31:16.603963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db1de479b63e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pansionats',
    sa.Column('pansionat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('pansionat_id')
    )
    op.create_table('residents',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('passport_series', sa.String(length=10), nullable=False),
    sa.Column('passport_number', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('planned_check_out', sa.Date(), nullable=False),
    sa.Column('actual_check_out', sa.Date(), nullable=True),
    sa.Column('check_in_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('room_types',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('room_type_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('pansionat_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['pansionat_id'], ['pansionats.pansionat_id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('beds',
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_label', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_resident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_resident_id'], ['residents.record_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('bed_id'),
    sa.UniqueConstraint('current_resident_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('future_res_last_name', sa.String(length=50), nullable=False),
    sa.Column('future_res_first_name', sa.String(length=50), nullable=False),
    sa.Column('future_res_mid_name', sa.String(length=50), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('planned_check_in', sa.Date(), nullable=False),
    sa.Column('planned_check_out', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.bed_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('beds')
    op.drop_table('rooms')
    op.drop_table('room_types')
    op.drop_table('residents')
    op.drop_table('pansionats')
    # ### end Alembic commands ###
